### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by LinZihong** [paulgavrikov/xiaomi-miband-cocoa#1]
Objective-C method 'centralManager:didDiscoverPeripheral:advertisementData:RSSI:' provided by method 'centralManager(_:didDiscoverPeripheral:advertisementData:RSSI:)' conflicts with optional requirement method 'centralManager(_:didDiscoverPeripheral:advertisementData:RSSI:)' in protocol 'CBCentralManagerDelegate'

**Comment by paulgavrikov** [comment]
I am not an Swift / ObjC expert, in fact it took me quite a while to do this small app.
But I guess you are implementing both methods (with rssi&adv and without) and this is a conflict. Just remove one of them or provide sourcecode. Maybe I can help.

**Comment by LinZihong** [comment]
I deleted 'central: CBCentralManager!' in the 'func centralManager(central: CBCentralManager!, didDiscoverPeripheral peripheral: CBPeripheral!, advertisementData: (NSDictionary), RSSI: NSNumber!)' and now the app can be compiled properly.
But still it cannot to my mi band. I'm guessing it's the problem of the firmware of the band

**Comment by paulgavrikov** [comment]
It worked also very unstable for me sometimes it paired, sometimes it didn’t.

**Comment by farique** [comment]
LinZihong, rename func to
func centralManager(central: CBCentralManager!, didDiscoverPeripheral peripheral: CBPeripheral!, advertisementData: [NSObject : AnyObject]!, RSSI: NSNumber!)

**Comment by Akhrameev** [comment]
@LinZihong renaming function to 

```
func centralManager(central: CBCentralManager, didDiscoverPeripheral peripheral: CBPeripheral, advertisementData: [String : AnyObject], RSSI: NSNumber)
```

fixed this issue for me (I just copied it from CBCentralManagerDelegate interface).
